spring:
  application:
    name: content-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://esaadkinan:____@cluster0.subirch.mongodb.net/content-database?retryWrites=true&w=majority
  graphql:
    graphiql:
      enabled: true
server:
  port: 8081
